
name: Unit testing

on:
  pull_request:
    branches:
      - main

jobs:
  FrontendTests:
    name: Tests for frontend app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Run Jest tests
        run: cd frontend && npm test