services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/code:ro
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - mongo
    environment:
      - POSTGRESQL_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_DB}?authSource=admin

  postgres:
    image: "postgres:17.2"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - ${POSTGRES_PORT}0:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  migrate:
    build: ./backend
    volumes:
      - ./backend/:/code:ro
    depends_on:
        - postgres
    command: ["alembic", "upgrade", "head"]
    environment:
      - POSTGRESQL_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}

  mongo:
    image: "mongo:7.0.16-rc1"
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}

volumes:
    postgres-data: