version: '3s'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/code:ro
    ports:
      - "8000:80"
    depends_on:
      - postgres
    environment:
      - POSTGRESQL_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}

  postgres:
    image: "postgres:17.2"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - ${POSTGRES_PORT}0:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
    postgres-data: