"""Added vertict to tests_history

Revision ID: 6b42e3df49b1
Revises: 0ff5f956ec67
Create Date: 2025-02-26 17:17:43.476841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b42e3df49b1'
down_revision: Union[str, None] = '0ff5f956ec67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests_history', sa.Column('verdict', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests_history', 'verdict')
    # ### end Alembic commands ###
