"""Added registered_by in users

Revision ID: c6e6a2d4927a
Revises: ceb32f086a31
Create Date: 2025-08-28 15:08:06.676820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e6a2d4927a'
down_revision: Union[str, None] = 'ceb32f086a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doctor_patients_id', table_name='doctor_patients')
    op.create_index(op.f('ix_doctor_patients_id'), 'doctor_patients', ['id'], unique=True)
    op.drop_constraint('doctor_patients_doctor_id_fkey', 'doctor_patients', type_='foreignkey')
    op.drop_constraint('doctor_patients_patient_id_fkey', 'doctor_patients', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_patients', 'users', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'doctor_patients', 'users', ['patient_id'], ['id'])
    op.drop_index('ix_patient_tests_id', table_name='patient_tests')
    op.create_index(op.f('ix_patient_tests_id'), 'patient_tests', ['id'], unique=True)
    op.drop_constraint('patient_tests_patient_id_fkey', 'patient_tests', type_='foreignkey')
    op.drop_constraint('patient_tests_assigned_by_id_fkey', 'patient_tests', type_='foreignkey')
    op.create_foreign_key(None, 'patient_tests', 'users', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'patient_tests', 'users', ['assigned_by_id'], ['id'])
    op.drop_index('ix_tests_history_id', table_name='tests_history')
    op.create_index(op.f('ix_tests_history_id'), 'tests_history', ['id'], unique=True)
    op.add_column('users', sa.Column('registered_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('registered_by_id', sa.Uuid(), nullable=True))
    op.drop_index('ix_users_id', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['registered_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'registered_by_id')
    op.drop_column('users', 'registered_at')
    op.drop_index(op.f('ix_tests_history_id'), table_name='tests_history')
    op.create_index('ix_tests_history_id', 'tests_history', ['id'], unique=False)
    op.drop_constraint(None, 'patient_tests', type_='foreignkey')
    op.drop_constraint(None, 'patient_tests', type_='foreignkey')
    op.create_foreign_key('patient_tests_assigned_by_id_fkey', 'patient_tests', 'users', ['assigned_by_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('patient_tests_patient_id_fkey', 'patient_tests', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_patient_tests_id'), table_name='patient_tests')
    op.create_index('ix_patient_tests_id', 'patient_tests', ['id'], unique=False)
    op.drop_constraint(None, 'doctor_patients', type_='foreignkey')
    op.drop_constraint(None, 'doctor_patients', type_='foreignkey')
    op.create_foreign_key('doctor_patients_patient_id_fkey', 'doctor_patients', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('doctor_patients_doctor_id_fkey', 'doctor_patients', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_doctor_patients_id'), table_name='doctor_patients')
    op.create_index('ix_doctor_patients_id', 'doctor_patients', ['id'], unique=False)
    # ### end Alembic commands ###
