"""Added deleted_at fields in user and doctor_patient

Revision ID: d7070b5fd83a
Revises: 33ceb7a86a74
Create Date: 2025-10-06 12:33:54.073444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7070b5fd83a'
down_revision: Union[str, None] = '33ceb7a86a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_patients', sa.Column('unassigned_at', sa.DateTime(), nullable=True))
    op.add_column('doctor_patients', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('doctor_patients', 'deleted_at')
    op.drop_column('doctor_patients', 'unassigned_at')
    # ### end Alembic commands ###
