name: Enhancement Request
description: Suggest a new feature or improvement
title: "[Enhancement] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea to improve something? Great! Help us understand your proposal.

  - type: input
    id: context
    attributes:
      label: Feature Area / Route
      description: What part of the project does this apply to?
      placeholder: e.g., /dashboard/doctor, TestResultCard, API logic
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the enhancement
      description: What would you like to see improved or added?
      placeholder: A clear and concise description of the feature or change.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this useful?
      description: How would this improve the project or user experience?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else you want to add? Links, mockups, etc.
    validations:
      required: false
