"""Added unassigned_at column to patient_tests

Revision ID: 0ff5f956ec67
Revises: 6a68e48220cc
Create Date: 2025-02-17 20:38:48.062629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff5f956ec67'
down_revision: Union[str, None] = '6a68e48220cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_tests', sa.Column('unassigned_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_tests', 'unassigned_at')
    # ### end Alembic commands ###
