"""Added tests_history table

Revision ID: 290fe72bd9a2
Revises: 17bc2ff07e5a
Create Date: 2025-01-23 17:26:59.788535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '290fe72bd9a2'
down_revision: Union[str, None] = '17bc2ff07e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('correct_points', sa.Integer(), nullable=False),
    sa.Column('passed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_history_id'), 'tests_history', ['id'], unique=False)
    op.create_index(op.f('ix_tests_history_patient_id'), 'tests_history', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_history_patient_id'), table_name='tests_history')
    op.drop_index(op.f('ix_tests_history_id'), table_name='tests_history')
    op.drop_table('tests_history')
    # ### end Alembic commands ###
