"""Added patient_test and doctor_patient table

Revision ID: 5fffd59bc212
Revises: 21cf29099b55
Create Date: 2025-01-22 14:42:12.549522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fffd59bc212'
down_revision: Union[str, None] = '21cf29099b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_patients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_patients_doctor_id'), 'doctor_patients', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_patients_id'), 'doctor_patients', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_patients_patient_id'), 'doctor_patients', ['patient_id'], unique=False)
    op.create_table('patient_tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_tests_id'), 'patient_tests', ['id'], unique=False)
    op.create_index(op.f('ix_patient_tests_patient_id'), 'patient_tests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_tests_test_id'), 'patient_tests', ['test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_tests_test_id'), table_name='patient_tests')
    op.drop_index(op.f('ix_patient_tests_patient_id'), table_name='patient_tests')
    op.drop_index(op.f('ix_patient_tests_id'), table_name='patient_tests')
    op.drop_table('patient_tests')
    op.drop_index(op.f('ix_doctor_patients_patient_id'), table_name='doctor_patients')
    op.drop_index(op.f('ix_doctor_patients_id'), table_name='doctor_patients')
    op.drop_index(op.f('ix_doctor_patients_doctor_id'), table_name='doctor_patients')
    op.drop_table('doctor_patients')
    # ### end Alembic commands ###
