"""Verdict as JSON

Revision ID: 98e13240c777
Revises: 6b42e3df49b1
Create Date: 2025-03-06 21:34:00.510442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e13240c777'
down_revision: Union[str, None] = '6b42e3df49b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            UPDATE tests_history
            SET verdict = '"' || verdict || '"'
            WHERE verdict IS NOT NULL AND verdict NOT LIKE '"%';
        """)
    op.alter_column('tests_history', 'verdict',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='verdict::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests_history', 'verdict',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
